[build]
  publish = "dist"
  command = "npm run generate"
[build.environment]
  NODE_VERSION = "14"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"